<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <script>

        // async function asyncFunction() { ... } - Это объявление асинхронной функции, которая позволяет использовать ключевое слово await внутри её тела. Это значит, 
        // что функция может ожидать выполнения асинхронных операций без блокировки выполнения других задач в приложении.

        // Асинхронная функция
        async function asyncFunction() {
            try {
                // const result = await someAsyncOperation(); - Здесь происходит ожидание выполнения асинхронной операции, представленной функцией someAsyncOperation. 
                // Это ожидание не блокирует выполнение программы, и выполнение asyncFunction приостанавливается до тех пор,
                // пока промис возвращенный someAsyncOperation не разрешится или не завершится с ошибкой.

                // Ожидание выполнения асинхронной операции (например, запроса к API)
                const result = await someAsyncOperation();

                // Возврат результата выполнения
                return result;

                // Если произойдет ошибка в ходе выполнения асинхронной операции, она будет перехвачена и передана в этот блок для обработки.
            } catch (error) {
                // Обработка ошибки, если она возникла
                throw error;
            }
        }
        //Функция someAsyncOperation имитирует асинхронную операцию и возвращает результат через промис.
        // Пример асинхронной операции (заглушка)
        function someAsyncOperation() {
            return new Promise((resolve) => {
                // Имитация асинхронной задержки
                setTimeout(() => {
                    resolve('Результат асинхронной операции');
                }, 1000);
            });
        }
        //При вызове asyncFunction, она ожидает выполнение someAsyncOperation, а затем возвращает результат выполнения. 
        //Мы используем .then() и .catch() для обработки результата или ошибки, которые могут возникнуть внутри асинхронной функции.
        // Пример использования асинхронной функции
        asyncFunction()
            .then((result) => {
                console.log('Результат:', result);
            })
            .catch((error) => {
                console.error('Ошибка:', error);
            });
            // В этой части кода мы вызываем асинхронную функцию asyncFunction. 
            // Когда промис возвращенный asyncFunction разрешается (успешно завершается), выполнится функция переданная методу .then(),
            // и результат асинхронной операции будет выведен на консоль. Если возникнет ошибка, будет вызвана функция переданная методу .catch(), 
            // и ошибка будет выведена на консоль.

    </script>
</body>

</html>